name: Build the container

on:
  workflow_dispatch:
    inputs:
      tag-name:
        description: 'The name of the tag to create'
        required: true
        type: string
      ref:
        description: 'The git reference to check out and build'
        required: false
        default: 'main'
        type: string
      push:
        description: 'Whether to push the built images'
        required: false
        default: true
        type: boolean

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          ref: ${{ inputs.ref }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1
      
      - name: Login to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
        with:
          platforms: linux/amd64,linux/arm64/v8 #,linux/arm/v7  - armv7 maven not working with qemu currently
          push: ${{ inputs.push }}
          tags: ghcr.io/kentyou/eclipse-sensinact:${{ inputs.tag-name }}
